// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250118204006_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.models.Ingrediente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Receitaid")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Receitaid");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("api.models.Receita", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("compatibilidade")
                        .HasColumnType("real");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("api.models.ReceitaIngrediente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("ingredienteId")
                        .HasColumnType("integer");

                    b.Property<int>("receitaId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ingredienteId");

                    b.HasIndex("receitaId");

                    b.ToTable("ReceitaIngrediente");
                });

            modelBuilder.Entity("api.models.Ingrediente", b =>
                {
                    b.HasOne("api.models.Receita", null)
                        .WithMany("ingredientes")
                        .HasForeignKey("Receitaid");
                });

            modelBuilder.Entity("api.models.ReceitaIngrediente", b =>
                {
                    b.HasOne("api.models.Ingrediente", "ingrediente")
                        .WithMany("receitaIngredientes")
                        .HasForeignKey("ingredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.models.Receita", "receita")
                        .WithMany("receitaIngredientes")
                        .HasForeignKey("receitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ingrediente");

                    b.Navigation("receita");
                });

            modelBuilder.Entity("api.models.Ingrediente", b =>
                {
                    b.Navigation("receitaIngredientes");
                });

            modelBuilder.Entity("api.models.Receita", b =>
                {
                    b.Navigation("ingredientes");

                    b.Navigation("receitaIngredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
